package com.game.game.domain;

public enum Phase {
    SETUP_TOKENS,
    SETUP_THORN,
    SETUP_UROCZYSKA,
    SETUP_INFLUENCE_1,
    SETUP_INFLUENCE_2,

    INITIATIVE,
    PLANNING_ORDER,
    PLANNING_ACTIONS,
    ACTION,
    UNIT_ACTIVATION,
    VUKO,
    DOMINATION
}
